### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by arozanski97** [seryrzu/tandem_aligner#1]
Hello,

I am trying to install on CentOS7 and ran into some issues.
I cloned the github repo, loaded gcc/8.2.0 and cmake 3.17.3, cd into tandem_aligner/tandem_aligner and ran make -j4
and I am receiving these errors

in `tandem_aligner/tandem_aligner/src/tools/suffix_array/suffix_array.hpp:27:41:`

```
error: ‘max_element’ is not a member of ‘std’
         value_type alphabet = 1 + *std::max_element(str.begin(), str.end());

```
in `tandem_aligner/tandem_aligner/src/projects/rare_kmer_aligner/rare_kmer_aligner.hpp:76:32:`

```
error: ‘const class std::unordered_set<__int128 unsigned, std::hash<__int128 unsigned>, std::equal_to<__int128 unsigned>, std::allocator<__int128 unsigned> >’ has no member named ‘contains’
                 if (rare_kmers.contains(hash)) {
```
Let me know if I can provide any additional information and thanks in advance!

**Comment by seryrzu** [comment]
Hi, it seems like you need a newer version of GCC. I have a github action that checks that GCC 9.4.0 works. Do you have a possibility to try it?

**Comment by arozanski97** [comment]
We were able to get GCC 9.4.0 and it worked, thank you!

**Comment by justdx** [comment]
Hi, I've encountered the same issue, which has generated an error message like the one below. I attempted to update GCC to version 9.4.0, but I'm still having the same problem. Could you please consider other potential sources of this error?
unialigner/tandem_aligner/src/tools/suffix_array/suffix_array.hpp:27:41: error: 'max_element' is not a member of 'std'
         value_type alphabet = 1 + *std::max_element(str.begin(), str.end());
